//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class TerminalCommandCd : ITerminalCommand {
	public TerminalCommandCd ()
	{
	}

	public void Execute (string[] args, TerminalController terminal) {
		if (args.Length != 2) {
			terminal.PrintString("You must specify what directory to change to!");
		} else {
			string dirName = args[1];

			if (dirName.Equals("..")) { // AS IT HAS BEEN FOR A THOUSAND YEARS
				if (terminal.workingDirectory.Count > 1) {
					terminal.workingDirectory.Pop ();
				} else {
					terminal.PrintString("You can't leave the file system! That's MADNESS!");
				}
			} else {
				TerminalFileData currentDirectory = terminal.workingDirectory.Peek();

				TerminalFileData nextDir = null;
				foreach(TerminalFileData child in currentDirectory.children) {
					if (child.name.Equals(dirName) && child.children != null) {	// no you can't change directory to a file named the same as a directory
						nextDir = child;
						break;
					}
				}

				if (nextDir != null) {
					terminal.workingDirectory.Push(nextDir);
				} else {
					terminal.PrintString(string.Format("No directory named \"{0}\"!", dirName));
				}
			}
		}
	}

	public string GetHelpString () {
		return "Usage:\ncd <directory>\n\nChange to a different directory.\nUse \"cd ..\" to go up a directory.";
	}
}


