//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class TerminalCommandLs : ITerminalCommand {
	public TerminalCommandLs ()
	{
	}

	public void Execute (string[] args, TerminalController terminal) {

		TerminalFileData current = terminal.workingDirectory.Peek();

		terminal.PrintString(string.Format("Contents of directory \"{0}\"", current.name));
		terminal.PrintString("======");
		terminal.PrintString("..\t\t-\t-");	// gotta have that ..
		if (current.children == null) {
			terminal.PrintString("ERROR READING DIRECTORY CONTENTS");
		} else {
			foreach (TerminalFileData file in current.children) {
				terminal.PrintString(string.Format ("{0}\t{1}\t{2}", file.name, file.owner, file.type));
			}
		}
	}

	public string GetHelpString () {
		return "Lists the files in your current directory";
	}
}


