//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

public class TerminalCommandHelp : ITerminalCommand {
	public TerminalCommandHelp ()
	{
	}

	public void Execute (string[] args, TerminalController terminal) {
		if (args.Length == 1) {
			terminal.PrintString("Type \"help\" plus a command to get more information about a command!");
			terminal.PrintString("Registered commands are:");

			StringBuilder builder = new StringBuilder();
			int i = 0;
			foreach (string command in terminal.commands.Keys) {
				i++;

				if (i % 3 == 0) {
					builder.Append("\n");
				}

				builder.AppendFormat("\t{0}", command);
			}

			terminal.PrintString(builder.ToString());
		} else if (args.Length == 2) {
			string helpCommand = args[1];

			if (terminal.commands.ContainsKey(helpCommand)) {
				ITerminalCommand command = terminal.commands[helpCommand];

				terminal.PrintString(string.Format ("Here is the help for \"{0}\":\n{1}", helpCommand, command.GetHelpString()));
			} else {
				terminal.PrintString("ERROR! Unknown command!");
			}

		} else {
			terminal.PrintString("ERROR! Specify only one command to get help about.");
		}
	}

	public string GetHelpString () {
		return "If you're asking that, you probably figured it out already";
	}
}


