//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections.Generic;

public class TerminalCommandPwd : ITerminalCommand {
	public TerminalCommandPwd ()
	{
	}

	public void Execute (string[] args, TerminalController terminal) {
		StringBuilder builder = new StringBuilder();

		TerminalFileData[] path = terminal.workingDirectory.ToArray();

		bool isFirst = true;
		foreach (TerminalFileData element in path) {
			if (isFirst) {
				builder.Append(element.name);
				isFirst = false;
			} else {
				builder.AppendFormat("/{0}", element.name);
			}
		}

		terminal.PrintString(builder.ToString());
	}

	public string GetHelpString () {
		return "Prints the current working directory.";
	}
}


