//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

// A nice way to keep track of information about a file - presently cosmetic
public class TerminalFileData {
	public string name;
	public string owner;
	public string type;
	public List<TerminalFileData> children;

	public TerminalFileData (string name, string owner, string type) {
		this.name = name;
		this.owner = owner;
		this.type = type;
		this.children = null;
	}

	public TerminalFileData (string name, string owner, List<TerminalFileData> children) {
		this.name = name;
		this.owner = owner;
		this.type = "DIRECTORY";
		this.children = children;
	}
}


